export const UPDATE_HTTP_METHOD = "UPDATE_HTTP_METHOD";
export const UPDATE_FORM = "UPDATE_FORM";
export const ADD_FORM_ELEMENT = "ADD_FORM_ELEMENT";
export const UPDATE_FORM_ELEMENT = "UPDATE_FORM_ELEMENT";
export const DELETE_FORM_ELEMENT = "DELETE_FORM_ELEMENT";
export const UPDATE_FORM_DETAILS = "UPDATE_FORM_DETAILS";
export const UPDATE_SCREEN = "UPDATE_SCREEN";
