# Generated by Django 4.0.6 on 2022-07-25 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('form_creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive')], default='draft', help_text='This form will be available to users only when status is active and the current date is between the start and end dates.', max_length=10),
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='seq_no',
            field=models.IntegerField(default=0, help_text='Order of the questions.', verbose_name='Order No.'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='form_responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='form_creator.formresponder'),
        ),
        migrations.AlterUniqueTogether(
            name='formquestion',
            unique_together={('form', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='formresponder',
            unique_together={('form', 'user')},
        ),
        migrations.CreateModel(
            name='HTMLComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_creator.form')),
            ],
            options={
                'verbose_name': 'HTML Component',
                'verbose_name_plural': 'HTML Components',
                'db_table': 'fc_html_component',
            },
        ),
        migrations.CreateModel(
            name='FormElementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_id', models.PositiveIntegerField()),
                ('seq_no', models.PositiveIntegerField()),
                ('element_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_creator.form')),
            ],
            options={
                'db_table': 'fc_form_element_order',
                'ordering': ('-form_id', 'seq_no'),
                'unique_together': {('form', 'seq_no')},
            },
        ),
    ]
