# Generated by Django 4.0.6 on 2022-07-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator', '0003_backfill_seq_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formquestion',
            options={'ordering': ['form']},
        ),
        migrations.RemoveField(
            model_name='formquestion',
            name='seq_no',
        ),
    ]
