# Generated by Django 4.0.5 on 2022-08-07 11:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_creator', '0004_alter_formquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formelementorder',
            name='form',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='form_creator.form'),
        ),
        migrations.AlterField(
            model_name='formelementorder',
            name='seq_no',
            field=models.PositiveIntegerField(default=None, help_text='The order in which the element is displayed (ordered in ascending order)', verbose_name='Sequence number'),
        ),
        migrations.AlterField(
            model_name='htmlcomponent',
            name='html',
            field=ckeditor.fields.RichTextField(verbose_name='HTML'),
        ),
    ]
